# ~/.config/starship.toml

add_newline = false
command_timeout = 2000

format = """
$os$username$hostname\
$directory\
$git_branch$git_status\
$kubernetes$docker_context\
$nodejs$java$golang$python$c$rust\
$cmd_duration
$character
"""

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "
vicmd_symbol = "[â®](bold yellow) "

[cmd_duration]
min_time = 2000
format = " â± [$duration]($style)"
style = "bold yellow"

[os]
format = "[$symbol](bold #fe4200) "
disabled = false
[os.symbols]
Windows = "î˜ª "
Arch = "ó°£‡ "
Ubuntu = "ïŒ› "
Macos = "ó°€µ "

[username]
format = "[$user]($style) "
style_user = "bold blue"
style_root = "bold red"
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname]($style) "
style = "bold yellow"
disabled = false

[directory]
format = "ğŸ“‚ [$path]($style) "
style = "bold fg:blue"
truncation_length = 2
truncation_symbol = "â€¦/"
home_symbol = "ó°‹œ ~"
read_only = " ï€£"
read_only_style = "bold red"

[git_branch]
symbol = "ï‡’ "
format = "[$symbol$branch]($style) "
style = "bold cyan"

[git_status]
format = '([$all_status$ahead_behind]($style)) '
style = "cyan"
conflicted = "âš¡"
up_to_date = "âœ”"
untracked = "ï”©"
ahead = "â‡¡${count}"
diverged = "â‡•"
behind = "â‡£${count}"
stashed = "î¬©"
modified = "ï„"
staged = "ï•"
renamed = "ïª¶"
deleted = "ï€”"

[kubernetes]
symbol = "ó±ƒ¾ "
format = "on [$symbol$context( $namespace)](bold purple) "
disabled = false

[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$context]($style) "
style = "bold blue"
disabled = false

[nodejs]
symbol = "îœ˜ "
format = "[$symbol$version](bold green) "
detect_files = ["package.json", "node_modules"]
disabled = false

[java]
symbol = "î‰– "
format = "[$symbol$version](bold red) "
detect_files = ["pom.xml", "build.gradle"]
disabled = false

[golang]
symbol = "î˜§ "
format = "[$symbol$version](bold cyan) "
detect_files = ["go.mod"]
disabled = false

[python]
symbol = "ó°¼¯ "
format = "[$symbol$version](bold blue) "
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile"]
disabled = false

[c]
symbol = "î˜ "
format = "[$symbol$version](bold yellow) "
detect_extensions = ["c", "cpp", "h", "hpp"]
disabled = false

[rust]
symbol = "î¨ "
format = "[$symbol$version](bold red) "
detect_files = ["Cargo.toml"]
disabled = false
